[package]
name = "gnbdu-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
mocks = { path = "../mocks" }
slog = "2.7.0"
anyhow = "1.0.63"
async-std = { version = "1.10.0", features = ["attributes"] }
common = { path = "../common" }
hex = "0.4.3"
