[package]
name = "sctp"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
slog = "2.7.0"
anyhow = "1.0.63"
os_socketaddr = "0.2.0"
libc = "^0.2"
async-io = "1.7.0"
errno = "0.2.8"
async-stream = "0.3.2"
futures-core = "0.3.19"
