[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
mocks = { path = "../mocks" }
gnbcu = { path = "../gnbcu" }
slog = "2.7.0"
anyhow = "1.0.64"
async-std = { version = "1.10.0", features = ["attributes"] }
common = { path = "../common" }
stop-token = "0.6.1"
serial_test = "0.8.0"
