[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
worker = { path = "../worker" }
coordinator = { path = "../coordinator" }
async-std = { version = "1.10.0", features = ["attributes","tokio02"] }
async-trait = "0.1.51"
slog = "2.7.0"
stop-token = "0.6.1"
backtrace = "0.3.63"
hex = "0.4.3"
async-channel = "1.6.1"
serde_json = "1.0.73"
bitvec = {version = "0.22", features = ["serde"] }
